// ======================================================================
// MATIÈRE : Pilotage de la Maintenance du SI (Master 2 — cas CampusCloud)
// ----------------------------------------------------------------------
// Ce fichier ne contient QUE des données : la fiche de la matière, ses domaines
// (THEMES), sa banque de QCM (BANK) et ses niveaux d'aventure (LEVELS).
// Le moteur du jeu (dossier js/) est commun à toutes les matières.
//
// Format d'une question : {q, a:[4 réponses], c:index bonne réponse (0-3), e:explication,
//                          d:difficulté 1|2|3 (3 = calcul/piège → chrono 30 s), ref:"Cours slide 20"}
// Vérification : node tools/check-bank.js
// ======================================================================
(function(){
"use strict";

// ---------- domaines (dans l'ordre des 7 modules du cours, puis le cas) ----------
var THEMES = [
  {id:"gouv",   name:"Gouvernance & planification", color:"#e0c35a"},
  {id:"maint",  name:"Maintenance du SI",      color:"#b06bff"},
  {id:"dispo",  name:"Disponibilité & SLA",    color:"#36c7d6"},
  {id:"supervision",name:"Supervision & dépendances", color:"#9be03a"},
  {id:"incident",name:"Gestion d'incident",    color:"#ff2e6a"},
  {id:"cab",    name:"Changement & CAB",       color:"#7a8cff"},
  {id:"cyber",  name:"NIST CSF & exercices de crise", color:"#ff6b4a"},
  {id:"doc",    name:"Documentation & CMDB",   color:"#5ad1b0"},
  {id:"bia",    name:"BIA · RTO / RPO",        color:"#ffab2e"},
  {id:"pcapra", name:"PCA vs PRA",             color:"#2ef0a6"},
  {id:"backup", name:"Sauvegardes",            color:"#ff7edb"},
  {id:"cas",    name:"Cas CampusCloud & roadmap", color:"#8fb3ff"}
];

var BANK = {
maint:[
  {q:"Une anomalie vient d'être détectée sur Moodle et on intervient pour la traiter. Quel type de maintenance ?", a:["Préventive conditionnelle","Évolutive","Curative","Corrective"], c:3, d:1, ref:"Cours slide 7", e:"Corrective = on traite une anomalie détectée (incident ou défaut confirmé) : diagnostic, contournement ou correction."},
  {q:"Renouveler un certificat avant son expiration relève de la maintenance…", a:["corrective, car l'expiration est une anomalie","évolutive","préventive","curative"], c:2, d:1, ref:"Cours slide 15", e:"Préventive = on agit avant la panne, ici sur un déclencheur calendaire : échéance de certificat, fin de support, revue périodique."},
  {q:"Adapter le SI à une nouvelle réglementation ou à de nouveaux usages relève de la maintenance…", a:["préventive déclenchée par le temps (échéance légale)","corrective","évolutive","curative"], c:2, d:2, ref:"Cours slide 7", e:"Évolutive = on adapte le service (capacité, sécurité, réglementation, nouveaux usages). Le signal est un besoin ou une opportunité."},
  {q:"Quelle différence entre maintenance corrective et curative ?", a:["Le correctif traite l'anomalie ; le curatif supprime durablement sa cause","Aucune : ce sont deux synonymes utilisés selon les entreprises","Le curatif intervient avant la panne, le correctif après","Le correctif concerne le matériel, le curatif concerne uniquement le logiciel"], c:0, d:2, ref:"Cours slide 7", e:"Un contournement rétablit vite (correctif), mais seul le curatif supprime la cause : réparer ou remplacer pour de bon."},
  {q:"Selon le cours, quelle est la bonne unité de pilotage de la maintenance ?", a:["L'actif technique (serveur, VM, licence)","Le nombre de tickets clos","Le budget de la DSI","Le service rendu"], c:3, d:1, ref:"Cours slide 6", e:"L'actif technique n'est qu'un moyen : on pilote la valeur du service pour le métier."},
  {q:"Quels sont les trois déclencheurs classiques de la maintenance préventive ?", a:["Le budget, le délai et le fournisseur","L'incident, le problème et le changement","Le temps, l'usage et le signal","La panne, l'alerte et la crise"], c:2, d:1, ref:"Cours slide 15", e:"Calendrier (certificat, sauvegarde), seuil d'usage (capacité, cycles) ou signal (erreurs, dérive, vulnérabilité)."},
  {q:"ITIL 4 est avant tout…", a:["une norme certifiante obligatoire pour toute DSI","un logiciel de gestion des tickets d'incident édité par PeopleCert","un cadre de bonnes pratiques organisé en système de valeur","une méthode de développement logiciel agile"], c:2, d:1, ref:"Cours slide 9", e:"ITIL 4 relie gouvernance, chaîne de valeur et pratiques (incident, changement, niveaux de service…). Ce n'est pas qu'une suite de tickets."},
  {q:"Dans le cycle de vie d'un service, la phase « Transitionner » consiste à…", a:["archiver les données et révoquer les accès","superviser le service et assurer l'astreinte","tester, documenter et définir les critères de retour arrière","définir les exigences de disponibilité et de support du service"], c:2, d:2, ref:"Cours slide 8", e:"Concevoir = exigences ; Transitionner = tests, doc, rollback ; Exploiter = supervision ; Maintenir = prévenir, corriger, faire évoluer ; Retirer = archiver."},
  {q:"Un service passe en production sans documentation ni supervision, car « le livrable fonctionne ». Quel principe est violé ?", a:["Le changement standard doit être préautorisé","Le SLA doit être signé par le client avant tout passage en production","L'escalade hiérarchique doit être déclenchée","La maintenabilité se construit avant la mise en production"], c:3, d:2, ref:"Cours slide 8", e:"Le passage en production doit transférer un service maintenable, pas seulement un livrable fonctionnel."},
  {q:"Une documentation opérationnelle utile est…", a:["exhaustive et la plus longue possible","stockée sur le poste de son auteur","trouvable, exécutable et maintenue","rédigée une fois pour toutes"], c:2, d:1, ref:"Cours slide 42", e:"Mieux vaut mesurer l'usage et la réussite d'une procédure que compter les pages produites."},
  {q:"Un inventaire exploitable doit permettre de répondre à quelles questions ?", a:["Quand, combien, pourquoi, comment ?","Qui achète, qui vend, qui paie, qui audite ?","Quel OS, quel CPU, quelle RAM, quel disque ?","Quoi, où, qui, et de quoi cela dépend ?"], c:3, d:1, ref:"Cours slide 12", e:"Actifs, localisation, propriétaires et dépendances. Un inventaire non maintenu devient une source de risque : sa fraîcheur est un KPI."},
  {q:"Dans la matrice de criticité du cours, quel actif faut-il « traiter en priorité » ?", a:["Impact métier élevé et reprise difficile","Impact faible mais reprise longue et coûteuse","Impact faible et reprise maîtrisée","Impact élevé mais reprise maîtrisée"], c:0, d:2, ref:"Cours slide 13", e:"Impact élevé + reprise difficile : réduire l'exposition, renforcer la redondance, tester le PRA. Impact élevé mais reprise maîtrisée = surveiller."},
  {q:"Que doit enchaîner chaque ligne d'un plan de maintenance robuste ?", a:["Budget → achat → livraison → facture","Risque → action → fenêtre → ressources → preuve","Alerte → ticket → diagnostic → clôture → archivage","Test → production → archivage"], c:1, d:2, ref:"Cours slide 14", e:"Le plan traduit le risque en calendrier, ressources et preuve ; il précise aussi responsable, statut, risque résiduel et prochaine revue."},
  {q:"Après trois pannes liées au même contrôleur disque, on remplace ce contrôleur. Type de maintenance ?", a:["Corrective","Préventive","Curative","Évolutive"], c:2, d:3, ref:"Cours slide 7", e:"Piège : on ne traite pas seulement l'anomalie (correctif), on supprime durablement sa cause (curatif)."}
],
dispo:[
  {q:"Qu'est-ce qu'un SLA ?", a:["Une mesure en temps réel de la disponibilité","Un accord avec le client : niveaux, plage, exclusions, responsabilités","Un objectif interne mesurable fixé par l'équipe d'exploitation pour une période","Un indicateur calculé à partir des données réelles"], c:1, d:1, ref:"Cours slide 21", e:"SLA = Service Level Agreement : l'engagement avec le client. L'objectif interne, c'est le SLO ; la mesure, c'est le SLI."},
  {q:"Quel énoncé distingue correctement SLI, SLO et SLA ?", a:["Le SLA mesure, le SLO encadre l'engagement, le SLI fixe la cible","Le SLI mesure, le SLO fixe la cible, le SLA encadre l'engagement","Le SLO mesure, le SLI fixe la cible, le SLA encadre l'engagement","Le SLI fixe la cible, le SLA mesure, le SLO encadre l'engagement contractuel"], c:1, d:2, ref:"Cours slide 21", e:"SLI = indicateur observé ; SLO = objectif mesurable ; SLA = accord avec conséquences."},
  {q:"Une disponibilité annuelle de 99,9 % autorise environ…", a:["52 minutes d'indisponibilité par an","3 jours d'indisponibilité par an","43 minutes d'indisponibilité par an","8 h 46 d'indisponibilité par an"], c:3, d:3, ref:"Cours slide 20", e:"8 760 h × 0,1 % ≈ 8,76 h. Chaque « 9 » supplémentaire divise la tolérance par environ 10 (99,99 % ≈ 52 min)."},
  {q:"Cible ≥ 99,5 % sur une fenêtre de 30 jours (720 h). Indisponibilité maximale tolérée ?", a:["36 minutes","7 h 12","3 h 36","21 h 36"], c:2, d:3, ref:"Cours slide 20", e:"720 h × 0,5 % = 3,6 h, soit 3 h 36. À 99 % on tolérerait 7 h 12."},
  {q:"La disponibilité se calcule comme…", a:["temps de service effectif ÷ temps de service prévu","temps de fonctionnement ÷ nombre de pannes","durée totale de réparation ÷ nombre d'incidents sur la période","MTTR ÷ MTBF"], c:0, d:2, ref:"Cas slide 11", e:"C'est la part de la fenêtre de service pendant laquelle le service est réellement utilisable. Les deux autres formules sont celles du MTBF et du MTTR."},
  {q:"Le MTTR mesure…", a:["l'intervalle moyen de fonctionnement entre deux pannes successives","la perte de données maximale acceptable","la latence réseau moyenne","le temps moyen de réparation ou de rétablissement"], c:3, d:1, ref:"Cours slide 20", e:"MTTR = Mean Time To Repair/Restore. Plus il est bas, plus on rétablit vite."},
  {q:"Le MTBF mesure…", a:["le temps moyen nécessaire pour réparer ou rétablir le service après une panne","la durée moyenne d'une sauvegarde","le taux d'erreur applicatif","le temps moyen de fonctionnement entre deux pannes"], c:3, d:1, ref:"Cours slide 20", e:"MTBF = Mean Time Between Failures : indicateur de fiabilité. Plus il est élevé, mieux c'est."},
  {q:"Sur 30 jours, un service subit 3 pannes pour 6 h d'indisponibilité cumulée. Son MTTR est de…", a:["6 h","18 minutes","10 jours","2 h"], c:3, d:3, ref:"Cas slide 11", e:"MTTR = durée totale de résolution ÷ nombre d'incidents = 6 h ÷ 3 = 2 h (cible du cas : ≤ 2 h)."},
  {q:"Période de 720 h, 4 pannes, 8 h d'indisponibilité cumulée. MTBF (temps de fonctionnement ÷ nombre de pannes) ?", a:["178 h","180 h","712 h","2 h"], c:0, d:3, ref:"Cours slide 20", e:"Temps de fonctionnement = 720 − 8 = 712 h ; 712 ÷ 4 = 178 h. Piège : 720 ÷ 4 = 180 h oublie de retirer les pannes."},
  {q:"Deux services ont la même disponibilité. Que peut-on conclure ?", a:["Ils ont forcément connu le même nombre de pannes et la même durée moyenne de réparation","Ils ont forcément le même MTBF","Leurs pannes peuvent être rares et longues pour l'un, fréquentes et brèves pour l'autre","Ils sont aussi fiables l'un que l'autre"], c:2, d:2, ref:"Cours slide 20", e:"À disponibilité égale, MTBF et MTTR peuvent différer fortement : d'où l'intérêt de lire les trois indicateurs."},
  {q:"Dans le cas CampusCloud, la cible du KPI de disponibilité est…", a:["≥ 99,5 % sur une fenêtre de 7 jours","≥ 99,9 % sur une fenêtre glissante de 12 mois","≥ 95 % avec une revue mensuelle","≤ 2 h sur une fenêtre de 4 semaines"], c:0, d:2, ref:"Cas slide 11", e:"Cible ≥ 99,5 %, fenêtre 7 j. Les autres KPI : MTTR ≤ 2 h (4 sem.), MTBF ≥ 14 j, SLA ≥ 95 % (revue mensuelle)."},
  {q:"Selon le cours, un KPI utile, c'est…", a:["un graphique de plus sur le tableau de bord","un SLA signé par le client","un SLI + une cible + une fenêtre + une décision associée","une métrique brute collectée automatiquement par l'outil de supervision"], c:2, d:2, ref:"Cas slide 11", e:"Un indicateur utile répond à une décision. Un SLI seul n'est qu'une mesure observée."},
  {q:"Pour interpréter un KPI de disponibilité, il faut toujours préciser…", a:["le nom de l'outil de supervision et la version de son agent de collecte","le nombre de serveurs supervisés et la fréquence exacte de collecte des métriques","la période, le périmètre et ce qui compte comme panne ou temps de réparation","uniquement la valeur moyenne du mois précédent"], c:2, d:2, ref:"Cours slide 20", e:"Sans définition précise, deux chiffres identiques peuvent désigner deux réalités différentes."},
  {q:"Cible de 99,95 % sur 30 jours (720 h). Indisponibilité maximale tolérée ?", a:["Environ 3 h 36","Environ 36 minutes","Environ 22 minutes","Environ 7 h 12"], c:2, d:3, ref:"Cours slide 20", e:"720 h × 0,05 % = 0,36 h ≈ 21,6 min. Piège : 3 h 36 correspond à 99,5 %."},
  {q:"Sur une fenêtre de 7 jours (168 h), Moodle a été indisponible 1 h. La cible du cas (≥ 99,5 %) est-elle tenue ?", a:["Oui : 99,9 %","Oui : 99,5 % exactement","Non : environ 99,4 %","Non : environ 98 %"], c:2, d:3, ref:"Cas slide 11", e:"167 ÷ 168 ≈ 99,40 %. Sur 7 jours, 99,5 % ne tolère que 50 minutes d'arrêt."},
  {q:"Un service a un MTBF de 198 h et un MTTR de 2 h. Sa disponibilité (MTBF ÷ (MTBF + MTTR)) vaut…", a:["99,9 %","99 %","98 %","99,5 %"], c:1, d:3, ref:"Cours slide 20", e:"198 ÷ (198 + 2) = 198 ÷ 200 = 99 %."}
],
bia:[
  {q:"Le BIA (Business Impact Analysis) sert à…", a:["identifier les activités vitales et mesurer les impacts d'une interruption","inventorier les vulnérabilités techniques des serveurs exposés sur Internet","dimensionner les serveurs pour les pics d'inscription","planifier les sauvegardes et leur rétention"], c:0, d:1, ref:"Cours slide 48", e:"Le BIA est le point de départ : il fixe les priorités avant de chiffrer RTO et RPO."},
  {q:"Le RTO est…", a:["le délai maximal acceptable pour rétablir le service","la quantité maximale de données qu'on accepte de perdre","le coût total de la restauration","le nombre de serveurs de secours"], c:0, d:1, ref:"Cours slide 49", e:"RTO = Recovery Time Objective : combien de temps le métier peut attendre avant la reprise."},
  {q:"Le RPO est…", a:["le délai maximal acceptable pour rétablir le service après interruption","la durée d'une sauvegarde complète","le nombre de copies conservées","la perte de données maximale acceptable, exprimée dans le temps"], c:3, d:1, ref:"Cours slide 49", e:"RPO = Recovery Point Objective : jusqu'où on accepte de remonter dans le passé. Il pilote fréquence et architecture de sauvegarde/réplication."},
  {q:"Un RPO de 1 heure impose au minimum…", a:["une reprise complète du service en moins d'une heure après l'incident","une sauvegarde quotidienne","une seule copie hors site","une sauvegarde ou réplication au moins toutes les heures"], c:3, d:2, ref:"Cours slide 49", e:"RPO 1 h = on tolère 1 h de données perdues au maximum : le point de sauvegarde doit être au plus à 1 h. Piège : la durée de reprise, c'est le RTO."},
  {q:"Un RTO de 15 minutes pour un service critique implique plutôt…", a:["une restauration manuelle depuis une sauvegarde externalisée sur bande","une sauvegarde complète toutes les 15 minutes","une procédure manuelle de mode dégradé uniquement","de la redondance ou une bascule automatique, donc un coût plus élevé"], c:3, d:2, ref:"Cours slide 49", e:"Plus la reprise doit être rapide, plus il faut investir (haute disponibilité, réplication, automatisation). Une sauvegarde toutes les 15 min répond à un RPO, pas à un RTO."},
  {q:"Quelle relation doit exister entre RTO et MTD (durée maximale d'interruption tolérable) ?", a:["Le RTO peut dépasser la MTD si le budget l'impose","Le RTO est toujours égal au RPO","La MTD se déduit du RTO","Le RTO doit rester inférieur ou égal à la MTD"], c:3, d:2, ref:"Cours slide 48", e:"La MTD est la limite absolue du métier ; le RTO est l'objectif de reprise qu'on se fixe pour rester en dessous."},
  {q:"Quel est l'ordre logique du raisonnement PRA/PCA ?", a:["BIA → impacts → RTO/RPO → stratégie → preuves","Stratégie → BIA → RTO/RPO → impacts → preuves","RTO/RPO → stratégie → BIA → preuves → impacts","Impacts → preuves → BIA → stratégie → RTO/RPO"], c:0, d:2, ref:"Cas slide 15", e:"On part des activités vitales, on mesure l'impact, on fixe les objectifs chiffrés, on choisit la stratégie, puis on prouve par des tests."},
  {q:"Les sauvegardes ont lieu une fois par nuit. Quel RPO réel peut-on promettre ?", a:["0 : la sauvegarde nocturne est complète","1 heure, si la sauvegarde est rapide","Environ 24 heures dans le pire cas","1 minute"], c:2, d:3, ref:"Cours slide 49", e:"Si l'incident survient juste avant la sauvegarde suivante, on perd presque 24 h de données."},
  {q:"Avec la formule du cas (score = 2×I + P + C − E), quel est le score de Moodle (I/P/C/E = 5/4/5/3) ?", a:["16","19","22","24"], c:0, d:3, ref:"Cas slides 04 et 07", e:"2×5 + 4 + 5 − 3 = 16. Piège : oublier de soustraire l'effort donne 19."},
  {q:"Quel actif a le score le plus élevé (2×I + P + C − E) ? Moodle 5/4/5/3 · ERP 5/3/5/4 · CRM 3/3/3/2 · Teams 3/2/3/2", a:["Moodle (16)","ERP (14)","CRM (10)","Teams (9)"], c:0, d:3, ref:"Cas slides 04 et 07", e:"Moodle 16 ; ERP 10+3+5−4 = 14 ; CRM 6+3+3−2 = 10 ; Teams 6+2+3−2 = 9. Le score oriente la discussion sans remplacer le jugement."},
  {q:"Dans cette formule, pourquoi l'effort (E) est-il soustrait ?", a:["À score égal, un effort élevé diminue la priorité immédiate (gains rapides d'abord)","Parce que E mesure l'exposition du service aux attaques, qui réduit mécaniquement sa valeur","Parce qu'un effort élevé prouve que le service est déjà bien maintenu","Ce n'est pas soustrait dans la formule"], c:0, d:2, ref:"Cas slide 07", e:"Un traitement coûteux est moins prioritaire qu'un traitement facile à impact comparable. Tester d'autres pondérations fait partie de l'exercice."},
  {q:"Quels impacts le BIA examine-t-il ?", a:["Uniquement l'impact financier","Uniquement techniques : CPU, mémoire, disque et réseau des serveurs","Financier, humain, légal, réputation et opérationnel","Uniquement les impacts sur la DSI"], c:2, d:1, ref:"Cours slide 48", e:"Le BIA regarde l'impact métier sous plusieurs angles avant de fixer tolérances (MTD) et exigences (RTO/RPO)."}
],
pcapra:[
  {q:"Le PCA (Plan de Continuité d'Activité) répond à la question…", a:["comment restaurer les serveurs, les données et les applications après un sinistre ?","comment poursuivre les activités essentielles, même en mode dégradé ?","comment chiffrer les sauvegardes ?","comment réduire le coût du cloud ?"], c:1, d:1, ref:"Cours slide 47", e:"Le PCA couvre processus, personnes, locaux, fournisseurs et procédures manuelles."},
  {q:"Le PRA (Plan de Reprise d'Activité) répond à la question…", a:["comment restaurer les services, données et infrastructures numériques ?","comment poursuivre l'activité avec des procédures manuelles pendant la panne ?","comment former les utilisateurs au mode dégradé ?","comment négocier les pénalités du SLA avec le fournisseur cloud ?"], c:0, d:1, ref:"Cours slide 47", e:"Le PRA s'appuie sur sauvegardes, réplication, site de secours ou reconstruction."},
  {q:"Le « mode dégradé » signifie…", a:["un arrêt complet du service en attendant la fin de la restauration du PRA","un service nominal sans restriction","un service réduit, mais l'activité essentielle est maintenue","la fin de la restauration"], c:2, d:1, ref:"Glossaire 8/10", e:"On continue avec des moyens réduits plutôt que de tout arrêter."},
  {q:"PCA et PRA sont…", a:["complémentaires : l'un maintient l'activité, l'autre rétablit les moyens numériques","deux noms différents pour le même plan, selon la norme utilisée","redondants : un PRA bien testé rend le PCA inutile, car l'activité ne s'arrête plus","opposés : on choisit l'un ou l'autre selon le budget"], c:0, d:2, ref:"Cours slide 47", e:"Ils ne répondent pas à la même question mais se complètent dans une crise."},
  {q:"Un PRA techniquement réussi peut malgré tout échouer si…", a:["le RPO est de 1 heure","le métier ne sait pas fonctionner pendant la reprise","les sauvegardes restaurées sont chiffrées avec une clé conservée hors site","les serveurs sont récents"], c:1, d:2, ref:"Cours slide 47", e:"Sans PCA, l'activité s'arrête pendant la restauration, même si la technique est parfaite."},
  {q:"Moodle est indisponible un jour d'examen. Quelle mesure relève du PCA ?", a:["Restaurer la VM Moodle depuis la dernière sauvegarde saine","Une procédure manuelle de secours pour poursuivre l'examen","Basculer Moodle sur le site de secours en répliquant la base","Purger les journaux"], c:1, d:2, ref:"Cours slide 47", e:"Le PCA maintient l'activité essentielle ; la restauration ou la bascule technique relève du PRA."},
  {q:"Restaurer une VM depuis une sauvegarde saine relève…", a:["du PRA","du PCA","du BIA","du RETEX"], c:0, d:1, ref:"Cours slide 47", e:"Le PRA rétablit les moyens numériques (données, services, infrastructure)."},
  {q:"Un PRA jamais testé est…", a:["une hypothèse non démontrée","fiable, puisqu'il est documenté et validé","conforme à ISO 22301 dès sa rédaction","inutile mais sans risque"], c:0, d:1, ref:"Cas slide 15", e:"Tester, mesurer, corriger : seule la preuve rend le plan crédible."},
  {q:"Qui fixe l'ordre de reprise des services ?", a:["La taille des VM, des plus petites aux plus grandes pour aller vite","Les priorités métier, vérifiées par la capacité technique réelle","L'équipe technique seule, selon la facilité de restauration","Le fournisseur cloud, selon son contrat"], c:1, d:2, ref:"Cours slide 47", e:"Les priorités métier fixent l'ordre ; la capacité technique vérifie ce qui est réaliste."},
  {q:"Pourquoi restaurer très tôt l'identité (Active Directory / Azure AD) dans un PRA ?", a:["De nombreux services en dépendent (SSO, accès) : sans elle, rien ne repart","Parce qu'elle est la plus petite et donc la plus rapide à restaurer en premier","Parce qu'elle coûte moins cher","Parce qu'elle n'a pas besoin de sauvegarde"], c:0, d:2, ref:"Cas slide 04", e:"Les dépendances bloquantes dictent l'ordre : AD et Azure AD sont notés 5 en impact et en continuité dans le cas."},
  {q:"ISO 22301 est…", a:["la norme relative aux processus de maintenance logicielle","la norme de management de la continuité d'activité","un guide de gestion des correctifs","un outil de supervision"], c:1, d:2, ref:"Glossaire 4/10", e:"ISO/IEC/IEEE 14764 concerne la maintenance logicielle ; NIST SP 800-40 les correctifs."},
  {q:"Dans un exercice de crise (cadrer, animer, évaluer), les « stimuli datés » relèvent de…", a:["le cadrage","l'évaluation","l'animation","la clôture"], c:2, d:2, ref:"Cas slide 15", e:"Cadrer : objectifs, participants, règles de sécurité. Animer : stimuli datés, observateurs. Évaluer : critères, RETEX à chaud/à froid, plan d'action."}
],
incident:[
  {q:"La priorité d'un incident découle…", a:["du nombre d'appels reçus","de l'impact et de l'urgence","de l'ancienneté du ticket","du niveau hiérarchique de la personne qui appelle"], c:1, d:1, ref:"Cours slide 26", e:"La priorité vient de l'impact et de l'urgence, pas du « volume sonore »."},
  {q:"Un incident P1 est…", a:["majeur : impact élevé mais contournement ou délai disponible","modéré : impact limité mais urgence réelle, résolution rapide avec contrôle du risque","faible : à regrouper et automatiser","critique : impact élevé et délai très court, escalade immédiate"], c:3, d:1, ref:"Cours slide 26", e:"P1 critique, P2 majeur (impact élevé, délai disponible), P3 modéré, P4 faible."},
  {q:"Quel est l'ordre du flux incident ?", a:["Détecter → diagnostiquer → qualifier → rétablir → clore","Qualifier → détecter → diagnostiquer → clore → rétablir","Détecter → qualifier → rétablir → diagnostiquer → clore","Détecter → qualifier → diagnostiquer → rétablir → clore"], c:3, d:2, ref:"Cours slide 27", e:"À chaque étape : horodatage, décision, responsable et prochain point de contrôle."},
  {q:"Le premier objectif du flux incident est…", a:["un rétablissement contrôlé du service ; la cause profonde peut être analysée ensuite","identifier la personne à l'origine de l'erreur afin d'éviter qu'elle ne se reproduise","identifier la cause racine avant toute action","fermer le ticket au plus vite"], c:0, d:2, ref:"Cours slide 27", e:"L'analyse de cause profonde peut se poursuivre après le retour du service."},
  {q:"Un contournement (workaround) est…", a:["la suppression définitive de la cause de l'incident par un remplacement","une sauvegarde de secours","une solution temporaire qui restaure le service sans supprimer la cause","un changement standard"], c:2, d:1, ref:"Glossaire 7/10", e:"Le contournement rétablit vite ; le curatif traitera la cause ensuite."},
  {q:"Appeler un expert réseau ou base de données relève de l'escalade…", a:["fonctionnelle","hiérarchique","de communication","contractuelle"], c:0, d:2, ref:"Cours slide 28", e:"Fonctionnelle = chercher l'expertise ; hiérarchique = obtenir priorité, ressources ou arbitrage de risque."},
  {q:"Obtenir un arbitrage de risque ou activer une cellule de crise relève de l'escalade…", a:["hiérarchique","fonctionnelle","technique","de communication"], c:0, d:2, ref:"Cours slide 28", e:"Escalade hiérarchique : mobiliser une autorité pour arbitrer priorité, ressources ou risque."},
  {q:"Quel est le rôle de l'Incident Manager ?", a:["Diagnostiquer et restaurer techniquement à la place des équipes","Prioriser et coordonner la résolution","Qualifier et tracer les tickets au guichet","Décider du budget annuel"], c:1, d:1, ref:"Cas slide 10", e:"Service Desk : qualifier, tracer, informer. N2/N3 : diagnostiquer, restaurer. Incident Manager : prioriser, coordonner."},
  {q:"Que doit conserver une main courante de crise ?", a:["L'heure, l'auteur, la décision, la preuve et la prochaine action","La liste des participants et leurs coordonnées, mise à jour à chaque réunion","Le détail des commandes exécutées par chaque administrateur","Une copie de chaque sauvegarde"], c:0, d:1, ref:"Cas slide 10", e:"Un seul fil rouge horodaté évite le bruit et permet le RETEX."},
  {q:"Une action de RETEX est considérée comme close quand…", a:["elle a été décidée en réunion","elle a été assignée à un responsable","le compte rendu a été diffusé","son efficacité est démontrée"], c:3, d:2, ref:"Cours slide 30", e:"Le RETEX produit des changements observables : faits, causes, barrières, actions, vérification."},
  {q:"À 08:20 le SSO devient instable, à 08:35 les inscriptions échouent, et un changement réseau a eu lieu la veille. Bonne posture ?", a:["Annuler immédiatement le changement réseau de la veille, forcément responsable de la panne","Qualifier périmètre et impact, et examiner le changement de la veille sans surinterpréter","Redémarrer tous les serveurs SSO","Attendre le prochain point de situation"], c:1, d:2, ref:"Cours slide 31", e:"Un changement récent est une hypothèse à vérifier, pas une certitude. On trace les décisions sur la main courante."},
  {q:"Dans la chronologie ransomware du cas, quel jalon suit la détection (T+0) ?", a:["T+30 : restauration priorisée","T+60 : communication","T+15 : confinement","T+120 : cellule de crise"], c:2, d:2, ref:"Cas slide 14", e:"T+0 détection · T+15 confinement · T+30 cellule de crise · T+60 communication · T+120 restauration priorisée."},
  {q:"Face à un ransomware, on isole les systèmes touchés…", a:["en éteignant et réinitialisant tout immédiatement","sans détruire les preuves","après avoir prévenu tous les utilisateurs par e-mail","uniquement après la restauration"], c:1, d:2, ref:"Cas slide 14", e:"Isoler sans détruire les preuves : l'investigation et la traçabilité en dépendent."},
  {q:"Impact limité mais urgence réelle (un TP noté démarre dans 30 minutes pour un seul groupe). Priorité ?", a:["P1 — critique","P2 — majeur","P3 — modéré","P4 — faible"], c:2, d:3, ref:"Cours slide 26", e:"Impact faible + urgence élevée = P3 : résolution rapide avec contrôle du risque."},
  {q:"Impact élevé, mais un contournement permet d'attendre quelques heures. Priorité ?", a:["P2 — majeur","P1 — critique","P3 — modéré","P4 — faible"], c:0, d:3, ref:"Cours slide 26", e:"Impact élevé + délai disponible = P2 : coordination renforcée et communication ciblée."},
  {q:"Dans le RETEX, l'étape « barrières » analyse…", a:["la chronologie et les impacts","ce qui a limité ou aggravé l'impact","le responsable et le délai des actions","le test qui prouve l'efficacité"], c:1, d:2, ref:"Cours slide 30", e:"Faits → causes → barrières → actions → vérifier."},
  {q:"Dans le cas « Panne Moodle », quelle étape suit « Impact confirmé » ?", a:["Service restauré","Décision d'escalade","Diagnostic lancé","Alerte reçue"], c:2, d:2, ref:"Cas slide 09", e:"Alerte reçue → impact confirmé → diagnostic lancé → décision d'escalade → service restauré."}
],
cab:[
  {q:"Une RFC est…", a:["une demande formalisée de changement permettant de l'évaluer et de l'autoriser","un rapport rédigé après le rétablissement d'un incident pour alimenter le RETEX","un rapport de sauvegarde","un accord de niveau de service"], c:0, d:1, ref:"Cours slide 34", e:"RFC = Request for Change."},
  {q:"Lequel de ces éléments n'est PAS attendu dans un dossier RFC ?", a:["La liste nominative des utilisateurs qui se connecteront après le changement","L'objectif et le périmètre","Le plan de test et l'observabilité","Le plan de retour arrière, sa durée chronométrée et son seuil de déclenchement"], c:0, d:2, ref:"Cas slide 13", e:"Dossier RFC : objectif, bénéfice, risques et dépendances, tests, pilote/vagues/communication, rollback + seuil."},
  {q:"Quel est le bon rôle du CAB ?", a:["Approuver formellement chaque changement avant sa mise en production, quel que soit son risque","Exécuter les changements","Remplacer l'Incident Manager","Conseiller et synchroniser les changements à fort enjeu, sans approuver chaque changement"], c:3, d:2, ref:"Cours slide 36", e:"Le CAB n'est pas un guichet : il intervient là où la pluralité des points de vue crée de la valeur."},
  {q:"Un changement standard est…", a:["soumis au CAB à chaque occurrence, même s'il est répétable","réservé aux urgences","interdit en production","préautorisé, répétable, à faible risque"], c:3, d:1, ref:"Cours slide 35", e:"Un changement fréquent ne devient standard qu'après preuve de répétabilité et de maîtrise."},
  {q:"Un changement urgent…", a:["est dispensé de documentation, puisque l'urgence prime sur la traçabilité","suit une voie accélérée pour protéger ou rétablir, avec décision tracée et revue a posteriori","attend la prochaine réunion du CAB, qui l'examine en priorité avant tous les autres changements","n'a jamais de rollback"], c:1, d:2, ref:"Cours slide 35", e:"L'urgence accélère la décision, pas l'absence de traçabilité."},
  {q:"Quelle est l'une des quatre questions posées au CAB pour une RFC critique ?", a:["Le prestataire choisi est-il le moins cher du marché ?","Le rollback est-il réaliste et chronométré ?","Le changement a-t-il été demandé par la direction ?","Le développeur a-t-il validé son code ?"], c:1, d:2, ref:"Cas slide 13", e:"Les 4 questions : risque compris ? preuve de test suffisante ? rollback réaliste et chronométré ? parties prenantes prêtes ?"},
  {q:"Déployer par pilote puis par vagues sert à…", a:["déployer partout en une seule fois pour réduire la durée totale d'indisponibilité","éviter d'écrire un rollback","remplacer le CAB","limiter le risque en validant sur un petit périmètre avant de généraliser"], c:3, d:1, ref:"Glossaire 9/10", e:"Le risque reste maîtrisé : on observe, puis on étend."},
  {q:"Un seuil de déclenchement du rollback est…", a:["le nombre maximal de personnes autorisées à intervenir pendant la fenêtre de changement","une condition objective (erreurs, latence…) qui décide du retour arrière","un nombre de serveurs","un budget maximum"], c:1, d:2, ref:"Cours slide 34", e:"C'est le signal mesurable qui dit « on annule » sans débat dans l'urgence."},
  {q:"Quelle décision peut prendre le CAB ?", a:["Approuver sans condition, puisque la RFC a déjà été rédigée et relue par l'équipe","Seulement refuser","Approuver ou reporter, avec conditions, pilote, seuil et prochain point de contrôle","Exécuter le changement lui-même"], c:2, d:2, ref:"Cas slide 13", e:"La décision est assortie de conditions explicites et d'un prochain point de contrôle."},
  {q:"Un correctif critique exige 20 minutes de redémarrage pendant les inscriptions. Meilleure posture ?", a:["Le déployer immédiatement sans consulter personne, car un correctif critique de sécurité ne peut jamais attendre","Le refuser définitivement","Attendre la prochaine année universitaire","Proposer pilote, fenêtre adaptée, observabilité et seuil de rollback, en répondant aux objections"], c:3, d:2, ref:"Cours slide 40", e:"On défend valeur, risque, dépendances et options, puis on formule une décision assortie de conditions."},
  {q:"Une fenêtre de maintenance est…", a:["la période pendant laquelle tout changement est interdit, sauf urgence","un tableau de bord de supervision","la période autorisée pour intervenir avec un impact convenu","un type de sauvegarde"], c:2, d:2, ref:"Glossaire 6/10", e:"Elle limite l'impact en choisissant un créneau validé avec le métier. La période où tout est interdit, c'est le gel."},
  {q:"La finalité de la gestion du changement est…", a:["de réduire le nombre total de changements pour limiter les incidents","d'augmenter le nombre de changements réussis","de bloquer toute nouveauté","de remplacer la CMDB"], c:1, d:2, ref:"Cours slide 33", e:"Le contrôle est proportionné à l'incertitude et à l'impact, sans immobiliser l'innovation."},
  {q:"Pendant la semaine d'examens, la DSI interdit tout changement non urgent. Comment s'appelle cette période ?", a:["Une fenêtre de maintenance","Un gel","Un pilote","Une vague"], c:1, d:2, ref:"Glossaire 9/10", e:"Le gel protège une période critique ; seuls les changements urgents, tracés, peuvent passer."},
  {q:"Dans une RFC, « la durée et le seuil de déclenchement » appartiennent au…", a:["plan de test","plan d'implémentation","plan de retour arrière","plan de communication"], c:2, d:2, ref:"Cours slide 34", e:"Un rollback crédible est chronométré et déclenché par une condition objective."}
],
backup:[
  {q:"La règle 3-2-1 de sauvegarde, c'est…", a:["3 sauvegardes par jour, conservées 2 semaines, dont 1 complète","3 copies, sur 2 supports différents, dont 1 hors site","3 serveurs, 2 sauvegardes, 1 restauration","1 seule copie bien protégée"], c:1, d:1, e:"La règle 3-2-1 résiste à la plupart des sinistres (panne, erreur, vol, incendie, ransomware)."},
  {q:"Quelle phrase est vraie ?", a:["Une sauvegarde présente n'est pas forcément restaurable","Une sauvegarde marquée « OK » dans le journal est forcément exploitable","Une sauvegarde chiffrée est forcément saine","Plus il y a de copies, moins il faut tester"], c:0, d:1, ref:"Cas slide 15", e:"Seul un test de restauration prouve qu'une sauvegarde est exploitable."},
  {q:"Pourquoi tester une restauration dans une zone isolée ?", a:["Gagner de la place disque","Accélérer la restauration en évitant les contrôles de sécurité de la production","Vérifier l'intégrité sans réinjecter un éventuel compromis en production","Éviter d'avoir à documenter"], c:2, d:2, ref:"Cas slide 14", e:"On contrôle que la copie est saine avant de la reconnecter au reste du SI."},
  {q:"Après une attaque, les sauvegardes récentes sont suspectes. Que faire ?", a:["Restaurer immédiatement la sauvegarde la plus récente pour réduire au maximum la perte de données","Vérifier l'intégrité en zone isolée et remonter vers une sauvegarde saine antérieure","Supprimer toutes les sauvegardes","Reconstruire tous les serveurs sans restaurer aucune donnée"], c:1, d:2, ref:"Cas slide 14", e:"Restaurer à l'aveugle peut réinjecter l'attaque : on vérifie l'intégrité avant toute remise en service."},
  {q:"Un snapshot est…", a:["une copie indépendante stockée hors site, équivalente à une sauvegarde complète","un contrat de service","un journal d'audit","une capture de l'état d'un système à un instant donné"], c:3, d:2, e:"Utile pour revenir vite en arrière, mais il ne remplace pas une sauvegarde indépendante."},
  {q:"Pour tenir un RPO de 4 heures, la sauvegarde doit avoir lieu…", a:["une fois par jour, avec une rétention de 4 jours","au moins toutes les 4 heures","une fois par semaine","une fois par mois"], c:1, d:2, ref:"Cours slide 49", e:"Le RPO donne l'écart maximal entre deux points de restauration. La rétention, c'est autre chose."},
  {q:"Pourquoi une copie hors ligne ou immuable protège-t-elle d'un ransomware ?", a:["Elle est plus rapide à restaurer que toutes les autres copies du SI","Elle ne peut être ni chiffrée ni effacée par l'attaquant","Elle coûte moins cher","Elle remplace le PRA"], c:1, d:2, e:"Une copie accessible depuis le SI compromis peut être chiffrée avec le reste."},
  {q:"Pourquoi la réplication ne remplace-t-elle pas la sauvegarde ?", a:["Elle ne fonctionne qu'entre deux équipements du même constructeur et du même modèle","Elle ne copie aucune donnée","Elle propage aussi les suppressions, corruptions et chiffrements","Elle est toujours plus lente"], c:2, d:2, e:"Une donnée chiffrée est répliquée telle quelle : seul un point de restauration antérieur permet de revenir."},
  {q:"Quelle preuve démontre qu'une sauvegarde est restaurable ?", a:["Le message « backup OK » envoyé chaque nuit par l'outil de sauvegarde","Le volume de données copié","La date de dernière exécution","Un test de restauration réussi, chronométré et documenté"], c:3, d:1, ref:"Cas slide 15", e:"On mesure aussi le temps réel de restauration pour le comparer au RTO."},
  {q:"La restauration d'un service dure 10 h pour un RTO de 4 h. Conclusion ?", a:["Tout va bien, puisque la donnée a finalement été restaurée sans perte","Le dispositif ne tient pas l'objectif : revoir la stratégie ou le RTO","Il suffit d'attendre","Le RPO est forcément respecté"], c:1, d:2, ref:"Cours slide 49", e:"Un test chronométré qui dépasse le RTO prouve un écart à traiter."},
  {q:"Un snapshot de la VM Moodle est stocké sur la même baie de stockage que la VM. Protège-t-il d'une panne de cette baie ?", a:["Oui, un snapshot est une sauvegarde complète","Non : il disparaît avec la baie ; il faut une copie indépendante","Oui, à condition qu'il ait été pris dans les 24 dernières heures avant la panne","Oui, s'il est chiffré"], c:1, d:3, e:"Un snapshot dépend de son support d'origine : c'est un retour arrière rapide, pas une sauvegarde indépendante (règle 3-2-1)."},
  {q:"Dans le plan annuel du cas, sur quelle ligne figurent les tests de sauvegarde et de reprise ?", a:["Préventif","Correctif","Évolutif","Continuité"], c:3, d:2, ref:"Cas slide 08", e:"Préventif : patches, contrôles · Correctif : réserve pour incidents · Évolutif : versions, migration · Continuité : tests de sauvegarde et de reprise."}
],
supervision:[
  {q:"Quels sont les trois niveaux d'une supervision utile ?", a:["Réseau, stockage et calcul","Expérience, service et composants","Matériel, système d'exploitation et application","Métier, juridique et financier"], c:1, d:1, ref:"Cours slide 18", e:"On part de ce que l'utilisateur doit réussir, puis on descend vers les composants explicatifs."},
  {q:"Collecter des métriques, est-ce superviser ?", a:["Non : chaque métrique doit mener à une décision","Oui, dès que les métriques sont stockées et consultables sur un tableau de bord","Oui, si on les conserve 5 ans","Non, il faut seulement plus d'écrans"], c:0, d:1, ref:"Cours slide 19", e:"Une donnée sans propriétaire ni décision associée crée du bruit, pas de la maîtrise."},
  {q:"Quelle est la chaîne de supervision complète ?", a:["Mesurer → détecter → contextualiser → apprendre → agir","Collecter → stocker → alerter → clore","Mesurer → contextualiser → détecter → agir → apprendre","Détecter → mesurer → agir → contextualiser → apprendre"], c:2, d:2, ref:"Cours slide 19", e:"La chaîne n'est complète que si réponse et apprentissage (seuils, runbooks, capacité) sont bouclés."},
  {q:"Qu'est-ce qui rend une alerte « actionnable » ?", a:["Gravité, contexte, propriétaire, délai et action attendue","Un envoi simultané à toute l'équipe par e-mail, SMS et messagerie","Un volume élevé de notifications","Une couleur rouge sur le tableau de bord"], c:0, d:1, ref:"Cours slide 23", e:"Avant d'ajouter une alerte, vérifier qu'une personne ou une automatisation sait quoi en faire."},
  {q:"Un trigger (déclencheur) est…", a:["un tableau de bord qui affiche l'historique des métriques collectées par l'outil","un rôle de la cellule de crise","une condition logique qui provoque une alerte dans l'outil de supervision","un contrat fournisseur"], c:2, d:1, ref:"Glossaire 6/10", e:"Quand la métrique franchit le seuil défini, la condition est vraie et l'alerte part."},
  {q:"Quel outil est décrit comme un moteur de checks extensible par plugins ?", a:["Grafana","Zabbix","Centreon","Nagios"], c:3, d:2, ref:"Cours slide 22", e:"Grafana : visualisation et alerting ; Zabbix : collecte, triggers, SLA ; Centreon : vues métier et rapports. Composer une chaîne cohérente est souvent plus réaliste qu'un outil unique."},
  {q:"Une « panne en cascade » est…", a:["une série de pannes indépendantes qui surviennent par hasard le même jour","une panne qui en entraîne d'autres par dépendances","une sauvegarde incrémentale","un rollback réussi"], c:1, d:1, ref:"Cours slide 31", e:"Un composant tombe et fait tomber ceux qui en dépendent : effet domino."},
  {q:"Pourquoi cartographier les dépendances ?", a:["Pour remplacer l'inventaire des actifs et la gestion des licences logicielles","Pour anticiper les impacts en chaîne d'une panne ou d'un changement","Pour réduire le nombre d'alertes","Pour se passer de supervision"], c:1, d:1, ref:"Cas slide 04", e:"Exemple du cas : si Active Directory / Azure AD tombe, l'authentification échoue et Moodle, l'ERP ou Microsoft 365 deviennent inaccessibles. Connaître les liens permet de prévoir ce qui tombera avec quoi."},
  {q:"À quoi sert la CMDB ?", a:["À stocker les métriques de supervision et à déclencher automatiquement les alertes","À planifier les astreintes de l'équipe","À relier les éléments de configuration et leurs dépendances pour analyser l'impact","À remplacer la supervision"], c:2, d:1, ref:"Cours slide 43", e:"La qualité des relations est décisive pour l'analyse d'impact des incidents et changements."},
  {q:"Que faut-il préciser pour chaque KPI ?", a:["Son nom, son unité et le nom de l'outil qui le collecte, sans autre précision nécessaire","Source, périmètre et période, formule, cible, fréquence de revue et décision déclenchée","Seulement sa valeur actuelle","Seulement sa tendance"], c:1, d:2, ref:"Cas slide 11", e:"Un KPI sans formule exacte ni décision associée est ambigu."},
  {q:"Par quoi doit commencer un bon tableau de bord ?", a:["L'ensemble des 35 métriques hebdomadaires, pour que le comité dispose de toute l'information disponible","La liste de tous les serveurs","Le graphique de disponibilité du mois","Un message de synthèse : ce qui change, pourquoi cela compte, quelle décision est attendue"], c:3, d:2, ref:"Cas slide 12", e:"Ensuite : tendance, écart à la cible, action et responsable. La visualisation vient après la définition."},
  {q:"Pour réduire le bruit d'alerting, on commence par…", a:["ajouter des alertes plus fines pour mieux couvrir chaque composant","désactiver la supervision la nuit","supprimer les alertes sans action claire","augmenter la rétention des logs"], c:2, d:2, ref:"Cours slide 23", e:"Réduire le bruit commence par supprimer les alertes dont personne ne sait quoi faire."},
  {q:"La panne perçue par l'utilisateur n'est pas toujours visible au niveau de sa cause. On analyse donc…", a:["uniquement le CPU des serveurs","des composants (CPU, mémoire, disque) vers l'expérience utilisateur","uniquement le datacenter","de l'expérience utilisateur vers les composants explicatifs"], c:3, d:2, ref:"Cours slide 18", e:"On commence par ce que l'utilisateur doit réussir, puis on descend service par service jusqu'à la cause."},
  {q:"Quel outil le cours décrit-il comme « visualisation multi-sources, alerting et suivi des SLO » ?", a:["Nagios","Zabbix","Centreon","Grafana"], c:3, d:2, ref:"Cours slide 22", e:"Nagios : checks par plugins · Zabbix : collecte, triggers, SLA · Centreon : vues métier et rapports · Grafana : visualisation et SLO."},
  {q:"Acquitter une alerte signifie…", a:["la supprimer définitivement","confirmer qu'elle a été prise en charge","la transférer automatiquement au fournisseur","augmenter son niveau de gravité"], c:1, d:1, ref:"Glossaire 7/10", e:"L'acquittement évite que plusieurs personnes traitent la même alerte ou que personne ne la traite."}
],
gouv:[
  {q:"Dans quel ordre se succèdent les phases du cycle de vie d'un service ?", a:["Concevoir → transitionner → exploiter → maintenir → retirer","Concevoir → exploiter → transitionner → retirer → maintenir","Transitionner → concevoir → maintenir → exploiter → retirer","Exploiter → concevoir → maintenir → transitionner → retirer"], c:0, d:1, ref:"Cours slide 8", e:"La maintenabilité se construit dès la conception et se mesure jusqu'au retrait."},
  {q:"Archiver, révoquer les accès et éliminer les dépendances : quelle phase du cycle de vie ?", a:["Exploiter","Transitionner","Retirer","Concevoir"], c:2, d:1, ref:"Cours slide 8", e:"Un retrait mal fait laisse des comptes actifs et des dépendances orphelines : c'est un risque de sécurité."},
  {q:"Dans le système de valeur ITIL 4, « fixer direction, politiques, appétence au risque et responsabilités » relève de…", a:["Pratiquer","Gouverner","Créer la valeur","Améliorer"], c:1, d:2, ref:"Cours slide 9", e:"Gouverner = direction et arbitrages ; Créer la valeur = chaîne de valeur ; Pratiquer = incident, changement, niveaux de service…"},
  {q:"L'« appétence au risque » d'une organisation, c'est…", a:["la liste des risques déjà survenus","le montant total des pertes subies par l'organisation lors de ses incidents passés","le niveau de risque qu'elle accepte pour atteindre ses objectifs","la probabilité qu'un incident se produise"], c:2, d:1, ref:"Glossaire 5/10", e:"Elle sert de repère pour décider : traiter, transférer, accepter ou éviter un risque."},
  {q:"On ajoute un second nœud au cluster Moodle. Il reste un risque de panne simultanée des deux nœuds. Comment l'appelle-t-on ?", a:["Un risque résiduel","Un risque inhérent supprimé","Une appétence au risque","Un risque transféré"], c:0, d:2, ref:"Glossaire 5/10", e:"Le risque résiduel est ce qui reste après traitement : il doit être connu, accepté et suivi."},
  {q:"Matrice de criticité : impact métier FAIBLE mais reprise COÛTEUSE. Que recommande le cours ?", a:["Traiter en priorité : renforcer la redondance et tester le PRA en urgence","Surveiller et conserver les preuves de test","Simplifier : retirer, remplacer ou réduire la complexité","Accepter tel quel sans action"], c:2, d:2, ref:"Cours slide 13", e:"Les 4 quadrants : traiter en priorité · surveiller · accepter/optimiser · simplifier."},
  {q:"Matrice de criticité : impact FAIBLE et reprise MAÎTRISÉE. Quelle orientation ?", a:["Accepter / optimiser : standardiser, automatiser, mutualiser","Renforcer immédiatement la redondance et planifier un test complet du PRA","Activer la cellule de crise","Retirer le service sans délai"], c:0, d:2, ref:"Cours slide 13", e:"Pas besoin de surinvestir : on industrialise ce qui est déjà sous contrôle."},
  {q:"Étendre le stockage dès que la base de données atteint 80 % de sa capacité : quel déclencheur préventif ?", a:["Le temps","Le signal","L'usage","L'incident"], c:2, d:3, ref:"Cours slide 15", e:"Piège : un seuil d'utilisation (capacité, cycles, volume) = USAGE. Le SIGNAL, c'est une tendance ou une anomalie (erreurs, dérive, vulnérabilité)."},
  {q:"Une vulnérabilité critique est publiée sur la version de l'hyperviseur VMware. Quel déclencheur préventif ?", a:["L'usage","Le temps","Le signal","Le budget"], c:2, d:2, ref:"Cours slide 15", e:"Une vulnérabilité, une dérive de performance ou une hausse d'erreurs sont des signaux qui déclenchent le préventif."},
  {q:"Le budget ne permet de traiter que 4 actifs sur 10 ce trimestre. Que faut-il formaliser pour les 6 autres ?", a:["Rien : ils seront traités l'an prochain","Le risque différé, ses hypothèses et la date de réévaluation","Uniquement une demande de budget supplémentaire adressée à la direction financière","La suppression des actifs non traités"], c:1, d:2, ref:"Atelier « Prioriser sous contrainte »", e:"Ne pas traiter est aussi une décision : elle doit être explicite, assumée et réexaminée."},
  {q:"Pourquoi tester la sensibilité d'un classement de criticité aux pondérations ?", a:["Pour obtenir le classement qui arrange l'équipe","Parce qu'ITIL 4 impose de recalculer chaque pondération à chaque comité de pilotage","Pour vérifier que la décision ne dépend pas d'un choix arbitraire de poids","Pour augmenter artificiellement les scores"], c:2, d:3, ref:"Atelier « Prioriser sous contrainte »", e:"Si le top 4 change complètement avec une petite variation de poids, la recommandation est fragile et doit être argumentée autrement."},
  {q:"Outre risque, action, fenêtre, ressources et preuve, que doit contenir chaque ligne d'un plan de maintenance ?", a:["Le nom du fournisseur le moins cher","Responsable, statut, risque résiduel et prochaine révision","La liste complète des serveurs du datacenter","Le numéro de ticket du dernier incident et le nom du technicien qui l'a traité"], c:1, d:2, ref:"Cours slide 14", e:"Chaque ligne doit pouvoir être pilotée sans dépendre de la mémoire de l'équipe."}
],
doc:[
  {q:"Un runbook est…", a:["un contrat de service signé avec un prestataire d'infogérance pour couvrir l'astreinte de nuit","un rapport d'audit annuel de la DSI","une procédure opérationnelle courte guidant diagnostic, action et validation","un tableau de bord de supervision temps réel"], c:2, d:1, ref:"Glossaire 8/10", e:"Une alerte actionnable renvoie idéalement vers son runbook : on sait quoi faire tout de suite."},
  {q:"Dans la CMDB, quel élément porte le contrat, le support et la dépendance externe ?", a:["Le service","L'application","La base de données","Le fournisseur"], c:3, d:2, ref:"Cours slide 43", e:"Chaîne type : Service (valeur, SLO) → Application → Base de données → Serveur/Cloud → Fournisseur (contrat, support)."},
  {q:"Qu'est-ce qui rend une CMDB vraiment utile pour analyser l'impact d'un incident ou d'un changement ?", a:["Le nombre total de CI enregistrés","La qualité des relations entre les CI","L'outil utilisé (ServiceNow, GLPI…)","La fréquence des exports Excel"], c:1, d:2, ref:"Cours slide 43", e:"Mille CI sans relations fiables ne disent pas « qui tombe avec quoi »."},
  {q:"Quel est l'ordre de la boucle éditoriale d'une base de connaissances ?", a:["Publier → capturer → utiliser → valider → améliorer","Valider → publier → capturer → améliorer → utiliser","Capturer → valider → publier → utiliser → améliorer","Utiliser → capturer → publier → améliorer → valider"], c:2, d:2, ref:"Cours slide 44", e:"La boucle part des situations réelles (incident, changement, question récurrente) et s'enrichit par le feedback."},
  {q:"Selon le cours, le meilleur article de base de connaissances est celui qui…", a:["est le plus détaillé techniquement","permet une action correcte, rapide et autonome","est validé par le plus grand nombre de personnes","est publié en premier après l'incident"], c:1, d:1, ref:"Cours slide 44", e:"La valeur d'un article se mesure par l'action qu'il rend possible, pas par sa longueur."},
  {q:"« Un tiers peut-il exécuter la procédure et produire une preuve de résultat ? » Quel critère d'audit documentaire ?", a:["La couverture","La fraîcheur","La responsabilité","La testabilité"], c:3, d:2, ref:"Cours slide 45", e:"Les 4 critères : couverture, fraîcheur, testabilité, responsabilité."},
  {q:"La procédure de restauration date d'avant la migration vers Azure Backup. Quel critère d'audit est en défaut ?", a:["La fraîcheur","La couverture","La testabilité","La traçabilité"], c:0, d:2, ref:"Cours slide 45", e:"Fraîcheur = la version reflète-t-elle l'environnement, les contacts et les dépendances actuels ?"},
  {q:"Quelles lacunes documentaires faut-il corriger en priorité ?", a:["Les plus anciennes, quel que soit le service","Celles des services les moins utilisés","Celles qui allongent le rétablissement ou augmentent le risque de changement","Celles signalées par l'auditeur externe lors de la dernière revue annuelle de conformité"], c:2, d:2, ref:"Cours slide 45", e:"On priorise par impact sur le MTTR et sur le risque, pas par ancienneté."},
  {q:"L'équipe annonce 400 pages de documentation rédigées ce trimestre. Quel indicateur serait plus utile ?", a:["Le nombre de mots par page","Le taux d'usage et de réussite des procédures lors des incidents","Le nombre d'auteurs différents","La taille totale du dossier partagé de documentation, mesurée en gigaoctets"], c:1, d:2, ref:"Cours slide 42", e:"Mesurer l'usage et la réussite d'une procédure est plus utile que compter les pages produites."},
  {q:"Pour qu'une procédure soit « trouvable », il faut surtout…", a:["l'imprimer et la ranger en salle serveur","l'envoyer par e-mail à toute l'équipe à chaque nouvelle version publiée","la lier depuis les alertes, tickets, CI et services concernés","la nommer avec la date du jour"], c:2, d:1, ref:"Cours slide 42", e:"Au moment critique, personne ne cherche : le lien doit arriver avec l'alerte ou le ticket."},
  {q:"Une procédure « exécutable » contient notamment…", a:["l'historique complet du projet, le budget consommé et les noms des développeurs","préconditions, étapes, validation, retour arrière et contacts","uniquement les commandes à copier-coller","un résumé pour la direction"], c:1, d:2, ref:"Cours slide 42", e:"Sans critère de validation ni retour arrière, on ne sait pas si l'action a réussi ni comment revenir en arrière."},
  {q:"La traçabilité, c'est la capacité à…", a:["retrouver l'origine, les décisions, les versions et les preuves","suivre en temps réel la position des équipes d'astreinte pendant une intervention","mesurer le temps de réponse d'une application","compter les connexions au SSO"], c:0, d:1, ref:"Glossaire 8/10", e:"Elle est exigée par la conformité et indispensable au RETEX."}
],
cyber:[
  {q:"Laquelle de ces fonctions ne fait PAS partie des six fonctions du NIST CSF 2.0 ?", a:["Gouverner","Détecter","Auditer","Récupérer"], c:2, d:2, ref:"Cours slide 37", e:"Les six fonctions : Gouverner, Identifier, Protéger, Détecter, Répondre, Récupérer."},
  {q:"Dans le NIST CSF 2.0, quelle fonction encadre toutes les autres ?", a:["Identifier","Protéger","Répondre","Gouverner"], c:3, d:2, ref:"Cours slide 37", e:"Gouverner (GOVERN) définit et supervise la stratégie de gestion des risques ; elle encadre identifier, protéger, détecter, répondre et récupérer."},
  {q:"Cartographier les données, le matériel et les logiciels relève de la fonction CSF…", a:["Identifier","Protéger","Détecter","Gouverner"], c:0, d:1, ref:"Cours slide 37", e:"On ne protège bien que ce que l'on connaît : c'est le lien avec l'inventaire du module 2."},
  {q:"Contrôle d'accès et formation des utilisateurs relèvent de la fonction CSF…", a:["Détecter","Répondre","Protéger","Identifier"], c:2, d:1, ref:"Cours slide 37", e:"Protéger = appliquer des mesures de sécurité qui réduisent la probabilité ou l'impact."},
  {q:"Quelle est la première étape de déploiement du NIST CSF ?", a:["Exécuter le plan d'action","Prioriser et délimiter : objectifs, actifs critiques, portée","Développer directement le profil cible à partir des pratiques du marché","Surveiller en continu"], c:1, d:2, ref:"Cours slide 38", e:"Ordre : prioriser/délimiter → état actuel → lacunes → risques → profil cible → plan d'action → surveillance continue."},
  {q:"Dans la démarche NIST CSF, le « profil cible » définit…", a:["la liste des attaquants connus","les résultats attendus et le niveau de maturité visé","l'état actuel des contrôles de sécurité déjà déployés dans l'organisation","le budget annuel de la DSI"], c:1, d:2, ref:"Cours slide 38", e:"On compare profil actuel et profil cible pour en déduire les lacunes à combler."},
  {q:"Couper l'accès réseau d'un serveur en cours de chiffrement relève…", a:["de la restauration","du confinement","du RETEX","de la communication"], c:1, d:2, ref:"Glossaire 10/10", e:"Confinement = limiter la propagation ou l'aggravation, sans détruire les preuves."},
  {q:"Informer les métiers, la direction et les partenaires pendant un incident relève de l'escalade…", a:["fonctionnelle","hiérarchique","de communication","technique"], c:2, d:2, ref:"Cours slide 28", e:"Trois escalades : fonctionnelle (expertise), hiérarchique (autorité, arbitrage), communication (informer les bons publics)."},
  {q:"Dans un exercice de crise, un « stimulus » est…", a:["une prime versée aux participants","une information injectée pour faire évoluer le scénario","le compte rendu final de l'exercice","la règle de sécurité qui permet d'interrompre l'exercice à tout moment"], c:1, d:1, ref:"Glossaire 10/10", e:"Le chronogramme de stimuli progressifs teste décision, communication et priorisation."},
  {q:"Quelle différence entre débriefing à chaud et débriefing à froid ?", a:["Aucune, ce sont deux noms du même temps","À chaud on recueille les observations fraîches ; à froid on consolide causes et actions","À chaud on désigne le responsable de l'incident ; à froid on décide de la sanction adaptée","Le débriefing à froid est facultatif"], c:1, d:2, ref:"Glossaire 10/10", e:"Le RETEX ne cherche pas de coupable : il produit des actions vérifiables."},
  {q:"Pourquoi l'exercice PRA doit-il « tester le système humain autant que la technique » ?", a:["Parce que la technique est toujours fiable","Pour évaluer individuellement chaque salarié et préparer les entretiens annuels de performance","Parce que décision, communication et coordination échouent souvent avant la restauration","Parce que la norme interdit les tests techniques"], c:2, d:2, ref:"Atelier « Tester le système humain »", e:"L'exercice révèle les écarts avant que la crise réelle ne les impose."},
  {q:"Un « point de situation » efficace, c'est…", a:["une réunion permanente qui réunit tous les acteurs sans interruption jusqu'à la fin de la crise","une synthèse courte et régulière : faits, impacts, actions, prochaines décisions","un e-mail envoyé une fois la crise terminée","le rapport technique détaillé de l'expert"], c:1, d:1, ref:"Cours slide 29", e:"Un point court et régulier vaut mieux qu'une réunion permanente sans décision."}
],
cas:[
  {q:"Sur l'échelle de maturité du cas, le niveau 4 « Mesuré » correspond à…", a:["des pratiques ad hoc","quelques routines non écrites","un pilotage par indicateurs","une boucle d'amélioration continue"], c:2, d:2, ref:"Cas slide 06", e:"1 Initial · 2 Répétable · 3 Défini · 4 Mesuré · 5 Amélioré."},
  {q:"Les incidents sont traités par habitude, sans procédure écrite, mais toujours par les mêmes personnes. Niveau de maturité ?", a:["1 · Initial","2 · Répétable","3 · Défini","4 · Mesuré"], c:1, d:3, ref:"Cas slide 06", e:"Piège : il existe des routines (≠ Initial), mais rien n'est documenté (≠ Défini)."},
  {q:"Dans l'audit, une note de maturité sans preuve devient…", a:["une note définitive","une hypothèse à valider","une non-conformité majeure","une note à arrondir au niveau supérieur"], c:1, d:1, ref:"Cas slide 06", e:"On demande des preuves (procédures, tickets, rapports de test) avant de conclure."},
  {q:"Lequel est un événement redouté bien formulé pour le registre des risques ?", a:["« Problème informatique »","« Le cloud »","« Indisponibilité de Moodle pendant une session d'examen »","« Sécurité insuffisante de l'ensemble du système d'information du campus »"], c:2, d:1, ref:"Cas slide 07", e:"Règle de qualité : un événement concret, puis distinguer cause, conséquence et mesure de maîtrise."},
  {q:"Avec score = 2×I + P + C − E, quel est le score de VMware (I/P/C/E = 5/4/5/5) ?", a:["19","14","24","9"], c:1, d:3, ref:"Cas slides 04 et 07", e:"2×5 + 4 + 5 − 5 = 14. Piège : 19 si on oublie de soustraire l'effort."},
  {q:"Moodle obtient 16 et Active Directory 15 avec la formule du cas. Faut-il traiter Moodle d'abord, sans discussion ?", a:["Oui : le score le plus élevé passe toujours en premier, c'est le principe même de la formule","Non : AD est une dépendance bloquante (SSO), le score oriente sans remplacer le jugement","Oui, car Moodle a plus d'utilisateurs","Non, il faut toujours traiter l'actif au score le plus bas"], c:1, d:3, ref:"Cours slide 13 · Cas slide 04", e:"La note doit rester explicable : si AD tombe, Moodle tombe aussi. Les dépendances peuvent inverser l'ordre."},
  {q:"Dans la matrice RACI du cas, « A » désigne la personne qui…", a:["exécute la tâche","apporte une expertise","répond du résultat","reçoit l'information"], c:2, d:2, ref:"Cas slide 10", e:"R exécute · A répond du résultat (une seule personne) · C apporte une expertise · I est informé."},
  {q:"Roadmap 12 mois : « automatisation, KPI et tests de reprise » relèvent de quelle phase ?", a:["0–3 mois · Sécuriser","3–6 mois · Stabiliser","6–9 mois · Industrialiser","9–12 mois · Optimiser"], c:2, d:2, ref:"Cas slide 16", e:"Sécuriser (urgences) → Stabiliser (processus, inventaire) → Industrialiser (automatisation, tests) → Optimiser (amélioration continue)."},
  {q:"Pourquoi les « actions urgentes à faible dépendance » sont-elles placées dans les 3 premiers mois ?", a:["Parce qu'elles réduisent vite le risque sans attendre d'autres chantiers","Parce qu'elles sont les plus chères","Parce que le CAB impose de traiter d'abord les changements les plus coûteux de l'année","Parce qu'elles n'ont pas besoin de propriétaire"], c:0, d:2, ref:"Cas slide 16", e:"Réduction du risque et dépendances font partie des six critères de séquencement."},
  {q:"Lequel n'est PAS un critère de séquencement de la roadmap du cas ?", a:["La capacité réelle des équipes à absorber la charge","Les dépendances","La preuve de réussite","La préférence technologique de l'équipe"], c:3, d:2, ref:"Cas slide 16", e:"Critères : réduction du risque, valeur métier, effort & coût, dépendances, capacité des équipes, preuve de réussite."},
  {q:"Ce mois-ci, 37 engagements sur 40 mesurés ont été respectés. Le KPI SLA (cible ≥ 95 %)…", a:["vaut 97,5 % : cible atteinte, aucune action requise","vaut 92,5 % : sous la cible, action à décider","vaut 95 % : cible tout juste atteinte","ne peut pas être calculé"], c:1, d:3, ref:"Cas slide 11", e:"KPI SLA = engagements respectés ÷ engagements mesurés = 37 ÷ 40 = 92,5 %."},
  {q:"Quel est le fil oral conseillé pour la soutenance finale ?", a:["Constat → risque → choix → preuve → roadmap","Roadmap → budget → outils → conclusion","Outils → architecture → démonstration → questions","Risque → coupable → sanction → plan"], c:0, d:2, ref:"Cas slide 17", e:"La meilleure réponse n'est pas la plus complexe : elle relie clairement risque, choix et preuve."}
]
};

// ======================================================================
// NIVEAUX DE L'AVENTURE — format texte, 1 caractère = 1 tuile de 18 px (12 lignes)
//    .  vide        #  sol (herbe auto)   =  plateforme      ^  piques (danger)
//    P  départ      X  sortie (drapeau)   C  cristal de données (→ QCM)
//    E  ennemi qui patrouille (saute dessus pour l'écraser)
//    Z  ennemi à pointes (impossible à écraser : évite-le… ou grille-le au pare-feu)
//    B  chauve-souris volante   H  ressort (maintiens SAUT pour aller très haut)
//    ?  bloc bonus : frappe-le par-dessous → Pare-feu (ou Bouclier PCA si tu l'as déjà)
//    u  bloc INVISIBLE (secret) → cœur +1 vie       o  octet (pièce, 30 = +1 vie)
//    K  clé de déchiffrement (secret : réunis les 3 !)
//    décor : t pin · g pousse · m champignon · w panneau · k cactus
//    themes = domaines du cours dont les cristaux tirent leurs QCM.
//    time = chrono du niveau en secondes (« RTO ») ; wave = front de ransomware qui avance.
// ======================================================================
var LEVELS = [
  {
    id:"dc", name:"Datacenter VMware", sub:"Gouvernance, maintenance, disponibilité & cas CampusCloud", themes:["gouv","maint","dispo","cas"], sky:["#1a0e3a","#3a1570"], accent:"#b06bff", time:140, hint:"Frappe le bloc « ! » par-dessous · saute sur les ennemis bleus · des secrets se cachent en hauteur…",
    map:[
      "........................................................................",
      "........................................................................",
      "............................................K...........................",
      "........................................................................",
      "........................................................................",
      "..............................B..........C..............................",
      "............?................u..........===.......................ooo...",
      "................oo...oC.o.......oo..............oo........C.............",
      "...............o..o..====...........===..................====...........",
      "..P..t..g..Ew..............^^.E.......E....wH.C.....m.E........Z..C..X..",
      "################..##############..##############..######################",
      "################..##############..##############..######################"
    ]
  },
  {
    id:"cloud", name:"Cloud Azure", sub:"Reprise, PCA/PRA, sauvegardes & documentation", themes:["bia","pcapra","backup","doc"], sky:["#0a2433","#13597a"], accent:"#36c7d6", time:170, hint:"Les octets (pièces) donnent une vie tous les 30 · maintiens SAUT sur un ressort pour aller très haut",
    map:[
      "........................................................................................",
      "........................................................................................",
      "........................................................K...............................",
      "............................................B...........................................",
      "..................................u...................................B.................",
      ".......................C....o................................................C..........",
      "........?..............o...===...oo........C............................o...o.o.........",
      "..................o...===.......====....=======...........C.................===.........",
      ".............o...===.................................oo..===...........===..............",
      "..P..t......===.........................E.^^^E...k......H....Z....===..............E.CX.",
      "##########............................###############..#########.................#######",
      "##########............................###############..#########.................#######"
    ]
  },
  {
    id:"crise", name:"Salle de crise", sub:"Incident, changement, supervision & NIST CSF", themes:["incident","cab","supervision","cyber"], sky:["#2a0a1e","#5a1240"], accent:"#ff2e6a", time:190, hint:"Le ransomware avance depuis la gauche : chaque bonne réponse le fait reculer · le pare-feu grille même les ennemis à pointes", wave:{"speed":12,"delay":5},
    map:[
      "................................................................................................",
      "................................................................................................",
      "....................................................K...........................................",
      "....................................B......C................B...................................",
      "......................................o.........................................................",
      "......................................C...===...................................................",
      ".........?......C..............................oo.................C.....?....C.............u....",
      "..............................oo.....===.......===................................o.............",
      "..............####...............................................####.......===..o.o............",
      "..P...g.......####...E.^^.Z.....===...............w.H.E.^.Z.C....####...E.^............E.....X..",
      "#############.####.##########......................#############.################...############",
      "#############.####.##########......................#############.################...############"
    ]
  }
];

// ---------- enregistrement de la matière auprès du moteur ----------
(window.CYBERCRISE_MATIERES = window.CYBERCRISE_MATIERES || []).push({
  id: "pilotage",                      // utilisé dans l'URL : index.html?matiere=pilotage
  icon: "🛠️",
  color: "#b06bff",
  name: "Pilotage de la Maintenance du SI",
  desc: "Gouverner, prévenir, superviser, rétablir et apprendre — à partir du cas fil rouge CampusCloud.",
  tags: ["7 modules", "Cas CampusCloud"],
  themes: THEMES,
  bank: BANK,
  levels: LEVELS
});
})();
